package wt

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.http.request.builder.HttpRequestBuilder

import scala.util.Random

object Actions {

  val webtours: HttpRequestBuilder = http("GET webtours")
    .get("/webtours/")
    .check(status.is(200))

  val welcome1: HttpRequestBuilder = http("GET welcome.pl-1")
    .get("/cgi-bin/welcome.pl")
    .queryParam("signOff","true")
    .check(status.is(200))

  val nav2: HttpRequestBuilder = http("GET nav.pl-2")
    .get("/cgi-bin/nav.pl")
    .queryParam("in","home")
    .check(regex("(?<=name=\"userSession\" value=\").+?(?=\")").saveAs("userSession"))
    .check(status.is(200))

  val login3: HttpRequestBuilder = http("POST login.pl-3")
    .post("/cgi-bin/login.pl")
    .formParam("userSession","#{userSession}")
    .formParam("username","w1mt23")
    .formParam("password","w1mt23")
    .formParam("login.x","53")
    .formParam("login.y","8")
    .formParam("JSFormSubmit","off")
    .check(status.is(200))

  val nav4: HttpRequestBuilder = http("GET nav.pl-4")
    .get("/cgi-bin/nav.pl")
    .queryParam("page","menu")
    .queryParam("in","home")
    .check(status.is(200))

  val login5: HttpRequestBuilder = http("GET login.pl-5")
    .get("/cgi-bin/login.pl")
    .queryParam("intro","true")
    .check(status.is(200))

  val welcome6: HttpRequestBuilder = http("GET welcome.pl-6")
    .get("/cgi-bin/welcome.pl")
    .queryParam("page","search")
    .check(status.is(200))

  val nav7: HttpRequestBuilder = http("GET nav.pl-7")
    .get("/cgi-bin/nav.pl")
    .queryParam("page","menu")
    .queryParam("in","flights")
    .check(status.is(200))

  val reservations8: HttpRequestBuilder = http("GET reservations.pl-8")
    .get("/cgi-bin/reservations.pl")
    .queryParam("page","welcome")
    .check(regex("(?<=value=\")(\\w+)(?=\">\\1)").findRandom.saveAs("departureCity"))
    .check(regex("(?<=value=\")(\\w+)(?=\">\\1)").findRandom.saveAs("arrivalCity"))
    .check(status.is(200))

  val reservations9: HttpRequestBuilder = http("POST reservations.pl-9")
    .post("/cgi-bin/reservations.pl")
    .formParam("advanceDiscount", "0")
    .formParam("depart", "#{departureCity}")
    .formParam("arrive", "#{arrivalCity}")
    .formParam("departDate", "06/02/2024")
    .formParam("returnDate", "06/03/2024")
    .formParam("numPassengers", "1")
    .formParam("seatPref", "Window")
    .formParam("seatType", "Business")
    .formParam("findFlights.x", "33")
    .formParam("findFlights.y", "5")
    .formParam(".cgifields", "roundtrip")
    .formParam(".cgifields", "seatType")
    .formParam(".cgifields", "seatPref")
    .check(regex("name=\"outboundFlight\" value=\"(.*?)\"").findRandom.saveAs("outboundFlight"))
    .check(status.is(200))

  val reservations10: HttpRequestBuilder = http("POST reservations.pl-10")
    .post("/cgi-bin/reservations.pl")
    .formParam("outboundFlight", "#{outboundFlight}")
    .formParam("numPassengers", "1")
    .formParam("advanceDiscount", "0")
    .formParam("returnDate", "06/02/2024")
    .formParam("numPassengers", "1")
    .formParam("seatPref", "Window")
    .formParam("seatType", "Business")
    .formParam("reserveFlights.x", "46")
    .formParam("reserveFlights.y", "9")
    .check(status.is(200))

  val reservations11: HttpRequestBuilder = http("POST reservations.pl-11")
    .post("/cgi-bin/reservations.pl")
    .formParam("firstName", "Danil")
    .formParam("lastName", "Idrisov")
    .formParam("address1", "w1mt23")
    .formParam("address2", "w1mt23")
    .formParam("pass1", "w1mt23 w1mt23")
    .formParam("creditCard", "")
    .formParam("expDate", "")
    .formParam("oldCCOption", "")
    .formParam("numPassengers", "1")
    .formParam("seatType", "Business")
    .formParam("seatPref", "Window")
    .formParam("outboundFlight", "#{outboundFlight}")
    .formParam("advanceDiscount", "0")
    .formParam("returnFlight", "")
    .formParam("JSFormSubmit", "off")
    .formParam("buyFlights.x", "60")
    .formParam("buyFlights.y", "11")
    .formParam(".cgifields", "saveCC")
    .check(status.is(200))

  val reservations12: HttpRequestBuilder = http("POST reservations.pl-12")
    .post("/cgi-bin/reservations.pl")
    .formParam("Book Another.x", "55")
    .formParam("Book Another.y", "14")
    .check(status.is(200))
}